# Generated by Django 4.2.5 on 2025-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_name",
            field=models.CharField(default="Uncategorized", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(default="Unnamed Product", max_length=255),
        ),
    ]
