# Generated by Django 4.2.5 on 2025-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_product_category_name_product_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="availability",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(default="2025-01-01"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_description",
            field=models.TextField(default="No product description"),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="seller_name",
            field=models.CharField(default="Unknown Seller", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="seller_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_cost",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.RemoveField(
            model_name="product",
            name="category_name",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description available"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="Unnamed Product", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="category_name",
            field=models.ManyToManyField(default=None, to="shop.category"),
        ),
    ]
