# Generated by Django 4.2.5 on 2025-01-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_alter_payment_payment_status_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_path",
            field=models.CharField(default="default.jpg", max_length=255),
        ),
    ]
