# Generated by Django 4.2.5 on 2025-01-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_product_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_path",
            field=models.CharField(max_length=255),
        ),
    ]
