# Generated by Django 4.2.5 on 2025-01-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_alter_product_image_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_path",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="products/"),
        ),
    ]
