# Generated by Django 4.2.5 on 2025-01-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_remove_product_image_path_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(max_length=255),
        ),
    ]
