# Generated by Django 5.1.5 on 2025-01-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(default="products/default.jpg", max_length=255),
        ),
    ]
